### ISSUE TITLE
verifySolution only prints warning once (per GAP session)

### ISSUE THREAD

**Issue by markuspf** [gap-packages/ferret#11]
* while preventing spam by displaying this warning only once during a computation, there should be a way to reset `printed_warning`?
* maybe the number of failed solutions should be counted? or even the examples collected?

**Comment by ChrisJefferson** [comment]
I have instead removed the warning. Now I've seen some examples (and put them in the tests), we don't need to warn about this any more.

Researchers might still want to see these cases, along with other stats, but we can hack that in when we want it (along with other stats)
