### ISSUE TITLE
Explain the names `ConStabilize` and `ConInGroup` in manual?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/ferret#20]
I am wondering what the logic behind the names `ConStabilize` and `ConInGroup` is. What does "Con" signify? My best guess is that this might be short for "Constraint". Is that it? Might be a good idea to document that, so that people can memorize it better. (Of course one might argue that the "GAPish" way would be to actually spell out the names, and only provide shorthands as additional synonyms ;-). But then one might also argue that the GAP way is to be inconsistent with oneself, so... ;-)

**Comment by ChrisJefferson** [comment]
improved
