### ISSUE TITLE
Extend README and convert to markdown

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/ferret#26]
The current version has only the title, which is not enough. Also, I suggest to rename it to README.md for better rendering on GitHub.

**Comment by ChrisJefferson** [comment]
Extended. Not markdown.

**Comment by alex-konovalov** [comment]
The content seems OK. Just to add that markdown is better displayed by GitHubPagesForGAP template, and also shows badges for CI tests (if added to README). But if you still do not want to convert it to `.md`, just close this again.

**Comment by ChrisJefferson** [comment]
It's fine.
