### ISSUE TITLE
Update meta-information

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/ferret#27]
In `PackageInfo.g`:
- fill in keywords
- update copyright year
- add abstract 
- maybe check dependencies (I suggest at least GAP 4.9, as we can test that on Travis)

Please see https://github.com/gap-packages/example/blob/master/PackageInfo.g for instructions.

**Comment by ChrisJefferson** [comment]
I'm not sure what you mean by "update copyright year"

**Comment by ChrisJefferson** [comment]
found it, removed it.
