### ISSUE TITLE
Manual: add examples of using `Solve`

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/ferret#9]
I think the manual should include some examples of how to use Solve properly. Trivial ones; more complex ones; and perhaps one or two which highlight its power.

As it is, while all "moving parts of the wheel" are described, it takes some time and uncertainty to fit them all together. Examples would help a great deal in figuring out how to use this.

**Comment by alex-konovalov** [comment]
Can't agree more. @ChrisJefferson please add these, we need to have them for the redistribution with GAP.

**Comment by ChrisJefferson** [comment]
done
